title: Nismos E2 Workshop
author: Nismo
email: nismogfx0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some curious coding and cleverness.

twitter_username: imquitedreaMY 
github_username:  NismoGraphics

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
exclude:
  - Gemfile
  - Gemfile.lock
